### ISSUE TITLE
Indication whether a sciencemesh contact is accepted is needed

### ISSUE THREAD

**Issue by mirekys** [pondersource/oc-sciencemesh#21] opened 2022-08-08 09:08 UTC
E.g. in my Reva contacts, I have:
<img width="840" alt="Screenshot 2022-08-08 at 11 03 42" src="https://user-images.githubusercontent.com/646743/183381473-ed8cd9a2-071c-4ac6-b6a3-df4ebbee3537.png">

We already accepted the invite links with Thirsa, when I click on her contact, it produces:
<img width="609" alt="Screenshot 2022-08-08 at 11 05 01" src="https://user-images.githubusercontent.com/646743/183381725-ecc608d0-1989-46f5-8529-44bfbe915029.png">

mostly because that invite requesst is already accepted:
<img width="379" alt="Screenshot 2022-08-08 at 11 05 41" src="https://user-images.githubusercontent.com/646743/183381856-52f42b70-a498-431e-8564-f68ec918f54d.png">

There should be some check that prevents accepting already accepted contacts & clear visual indication, whether a contact still needs to be accepted, or is already accepted.

**Comment by michielbdejong** [comment] 2022-08-10 06:22
Yes! Good point. @navid-dada or @mrvahedi68 can you have a look at this?

**Comment by navid-dada** [comment] 2022-08-10 07:38
this functionality is also added to nc-sciencemesh. I have no idea about what this feature should be. can you tell us some more details ?

**Comment by mirekys** [comment] 2022-08-10 08:14
> this functionality is also added to nc-sciencemesh. I have no idea about what this feature should be. can you tell us some more details ?
<img width="621" alt="Screenshot 2022-08-10 at 10 13 02" src="https://user-images.githubusercontent.com/646743/183850618-bad21b99-c678-4e7f-9c12-7cdac3f3e8db.png">

just a quick mockup of how things could work

**Comment by navid-dada** [comment] 2022-08-10 08:21
so, as I know, the contact flow is half-duplex. it means "einstein" created an invitation link and sends it to Marie. when Marie accepts the invitation link there is no contact item in Marie's contacts list. just there is one new item in the "Einstein" contacts list which refers to Marie. @michielbdejong, is it correct?

**Comment by michielbdejong** [comment] 2022-08-10 08:37
I think in this case Miroslav plays the role of Einstein and Thirsa plays the role of Marie.
It seems that Thirsa already accepted Miroslav's invite, Thirsa is in Miroslav's Contacts list.

It seems that clicking Thirsa in Miroslav's Contacts is triggering an attempt to resend the invite, which would obviously wrong then, if she is already a contact?

**Comment by mirekys** [comment] 2022-08-10 11:39
> I think in this case Miroslav plays the role of Einstein and Thirsa plays the role of Marie. It seems that Thirsa already accepted Miroslav's invite, Thirsa is in Miroslav's Contacts list.
> 
> It seems that clicking Thirsa in Miroslav's Contacts is triggering an attempt to resend the invite, which would obviously wrong then, if she is already a contact?

It makes a POST to `/index.php/apps/sciencemesh/contacts/accept` endpoint to somehow 'accept the contact' - that's what got me confused, when both of us already accepted invites using the generated URL links. I can't think of a case, when a non-accepted contact may appear in my list (my reva IOP has no way of knowing, who may accept the invitation link I created, at which site, before it is accepted), is there any such case I'm not aware of?

**Comment by michielbdejong** [comment] 2022-08-15 08:45
No, this click handler just showed up there by accident. I think it was an accidental copy-paste from the template/js code of the pending invites view.

@mrvahedi68 are you working on removing it, both in oc-sciencemesh and nc-sciencemesh?

**Comment by michielbdejong** [comment] 2022-08-15 09:22
No, this click handler just showed up there by accident. I think it was an accidental copy-paste from the template/js code of the pending invites view.

@mrvahedi68 are you working on removing it, both in oc-sciencemesh and nc-sciencemesh?

**Comment by navid-dada** [comment] 2022-08-15 09:27
I think @mrvahedi68 is not working on NC-sciencemesh. I will remove that part of the code. it will be done until tomorrow.

**Comment by navid-dada** [comment] 2022-08-18 11:31
the issue is closed by @mrvahedi68 's commit.

**Closed** 2022-08-18 11:30 UTC
